In [15]:
import numpy as np
import pandas as pd
import os
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

In [16]:
seasondata = pd.read_csv('../Positions by Game/2020-2021_positions_by_game')

In [18]:

y = seasondata['Winner'].values
X = seasondata[['F_home_assists','F_home_goals',
                                'F_home_pim',
                                'F_home_shots',
                                'F_home_blocked',
                                'F_home_pm',
                                'D_home_assists',
                                 'D_home_goals',
                                'D_home_pim',
                                'D_home_shots',
                                'D_home_blocked',
                                'D_home_hits',
                                'D_home_pm',
                                'G_home_GAA',
                                'F_away_assists',
                                'F_away_goals',
                                'F_away_pim',
                                'F_away_shots',
                                'F_away_blocked',
                                'F_away_hits',
                                'F_away_pm',
                                'D_away_assists',
                                'D_away_goals',
                                'D_away_pim',
                                'D_away_shots',
                                'D_away_blocked',
                                'D_away_hits',
                                'D_away_pm',
                                'G_away_GAA']]
X_train, X_test, y_train, y_test = train_test_split(X,y,
                                                   test_size = .2,
                                                   shuffle = True,
                                                   stratify = y,
                                                   random_state=973)

In [13]:
y

array([0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1,
       0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1,

In [53]:
logreg = LogisticRegression(max_iter = 100000,
                           C = .01)
logreg.fit(X_train,y_train)
y_pred = logreg.predict(X_test)

In [54]:
from sklearn.metrics import confusion_matrix,precision_score,accuracy_score

In [55]:
conf_mat = confusion_matrix(y_test,y_pred)
conf_mat

array([[70, 32],
       [52, 37]], dtype=int64)

In [56]:
precision_score(y_test,y_pred)

0.5362318840579711

In [57]:
accuracy_score(y_test,y_pred)

0.5602094240837696

In [58]:
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

In [59]:
logreg_pca = LogisticRegression(max_iter = 100000,
                               C = .01)
scaler = StandardScaler()
scaler.fit(X_train)
X_train_scaled = scaler.transform(X_train)

pca = PCA(n_components = .99)

pca.fit(X_train_scaled)

X_train_pca = pca.transform(X_train_scaled)

logreg_pca.fit(X_train_pca,y_train)

LogisticRegression(C=0.01, max_iter=100000)

In [62]:
X_test_scaled = scaler.transform(X_test)
X_test_pca = pca.transform(X_test_scaled)
y_pred_pca = logreg_pca.predict(X_test_pca)

In [64]:
conf_mat = confusion_matrix(y_test,y_pred_pca)
conf_mat

array([[69, 33],
       [48, 41]], dtype=int64)

In [65]:
accuracy_score(y_test,y_pred_pca)

0.5759162303664922

In [66]:
precision_score(y_test,y_pred_pca)

0.5540540540540541